# Generated by Django 3.2.16 on 2022-12-13 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(default='08:00', max_length=10),
        ),
    ]
