# Generated by Django 3.2.16 on 2022-12-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_no_of_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_persons',
            field=models.IntegerField(),
        ),
    ]
