# Generated by Django 3.2.16 on 2023-01-03 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='full_name',
            new_name='user',
        ),
    ]
